### ISSUE TITLE
Installation done but nothing displayed (with solution)

### ISSUE THREAD

**Issue by TrickMyIdea** [pklink/Dingbat#6]
First of all, great small tool to manage todo list. Being a developer, it makes easy to manage own as well as team tasks.

Issue: Installation done and I can see the 'Light bulb' but no tasks.

Problem: jquery.keycut.min.js not loading

Reason: I have installed it in a sub directory but the path is set to '/js/vendor/jquery.keycut.min.js' in layout.php

Solution: remove slash and set the path as 'js/vendor/jquery.keycut.min.js'

**Comment by pklink** [comment]
Thank you!
